export const demoProfile = {
  name: "Alex Morgan", role: "Staff Platform Engineer", location: "Austin, TX",
  resumeText: "Platform engineer with Go, Kubernetes, AWS, observability, and developer tooling experience.",
  preferences: { workStyle: "Remote", minCompensation: 140000 }
};

export const demoJobs = [
  { id: "job-1", title: "Staff Platform Engineer", company: "Vercel", logo: "V", location: "Remote · United States", workStyle: "Remote", compensation: "$185k – $235k", compensation_max: 235000, posted: "3h ago", collectedAt: "3 minutes ago", source: "Vercel Careers", sourceUrl: "https://vercel.com/careers", description: "Own the next generation of developer infrastructure used by teams shipping ambitious products. Partner with product and security to make deployments faster, safer, and observable.", tags: ["Go", "Kubernetes", "AWS", "Observability"], semanticFit: 0.97, constraintFit: 0.96, preferenceFit: 0.92, freshness: 0.99, growthFit: 0.94, reasons: ["8 of 9 target skills found", "Remote within the US", "Salary clears your $140k floor", "Posted and verified 3 hours ago"], risks: ["Leadership scope is implied, not explicit"] },
  { id: "job-2", title: "Senior Software Engineer, Developer Experience", company: "GitLab", logo: "G", location: "Remote · Americas", workStyle: "Remote", compensation: "$156k – $210k", compensation_max: 210000, posted: "1d ago", collectedAt: "7 minutes ago", source: "GitLab Careers", sourceUrl: "https://about.gitlab.com/jobs/", description: "Build tools and workflows that help every engineer ship with confidence. Improve local development, CI feedback loops, and the platform experience across a distributed team.", tags: ["Developer Tools", "CI/CD", "TypeScript", "Remote-first"], semanticFit: 0.89, constraintFit: 0.95, preferenceFit: 0.89, freshness: 0.94, growthFit: 0.9, reasons: ["Strong developer tooling overlap", "Remote-first culture", "Compensation matches your range"], risks: ["Role is one level below your target", "Travel expectation is unclear"] },
  { id: "job-3", title: "Principal Infrastructure Engineer", company: "Cloudflare", logo: "C", location: "Austin, TX · Hybrid", workStyle: "Hybrid", compensation: "$205k – $278k", compensation_max: 278000, posted: "2d ago", collectedAt: "11 minutes ago", source: "Cloudflare Careers", sourceUrl: "https://www.cloudflare.com/careers/jobs/", description: "Shape the systems and standards behind a global edge network. Lead architecture decisions across reliability, capacity planning, and platform engineering.", tags: ["Infrastructure", "Reliability", "Architecture", "Austin"], semanticFit: 0.87, constraintFit: 0.73, preferenceFit: 0.82, freshness: 0.9, growthFit: 0.98, reasons: ["Exceptional growth fit", "Compensation is well above target", "Austin office matches your radius"], risks: ["Hybrid: 2 days/week in office", "Principal scope may require larger-team leadership"] },
  { id: "job-4", title: "Platform Engineer, Internal Tools", company: "Figma", logo: "F", location: "New York, NY · Hybrid", workStyle: "Hybrid", compensation: "$170k – $225k", compensation_max: 225000, posted: "4d ago", collectedAt: "18 minutes ago", source: "Figma Careers", sourceUrl: "https://www.figma.com/careers/", description: "Make the development experience delightful for a growing engineering organization through self-service platforms, paved roads, and thoughtful automation.", tags: ["Platform", "Internal Tools", "Python", "Product-minded"], semanticFit: 0.82, constraintFit: 0.54, preferenceFit: 0.72, freshness: 0.78, growthFit: 0.86, reasons: ["Strong internal tools match", "Product-minded engineering culture"], risks: ["New York location conflicts with your Austin radius", "Listing has not been updated in 4 days"] }
];
